#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Sep  3 23:42:17 2018

@author: root
"""


Administering a WebSphere Commerce Site	Commerce	https://yourlearning.w3bmix.ibm.com/#search/activities/q=6G50G
Administering the WebSphere Commerce Database for WebSphere Commerce V7 FEP 8	Commerce	https://yourlearning.w3bmix.ibm.com/#search/activities/q=6G53G
IBM Payments for WebSphere Commerce for WebSphere Commerce V7 for Feature Pack 8	Commerce	https://yourlearning.w3bmix.ibm.com/#search/activities/q=6G58G
Managing features for IBM WebSphere Commerce Version 7 FEP 8	Commerce	https://yourlearning.w3bmix.ibm.com/#search/activities/q=6G52G
WebSphere B2B Administration	Commerce	https://yourlearning.w3bmix.ibm.com/#search/activities/q=6G49G
WebSphere Commerce Build and Deployment	Commerce	https://yourlearning.w3bmix.ibm.com/#search/activities/q=6G47G
WebSphere Commerce Search Administration	Commerce	https://yourlearning.w3bmix.ibm.com/#search/activities/q=6G55G
WebSphere Commerce Security and Auditing	Commerce	https://yourlearning.w3bmix.ibm.com/#search/activities/q=6G56G
WebSphere Commerce Server Caching for WebSphere Commerce V7 for Feature Pack 8	Commerce	https://yourlearning.w3bmix.ibm.com/#search/activities/q=6G54G
WebSphere Commerce Server Performance	Commerce	https://yourlearning.w3bmix.ibm.com/#search/activities/q=6G57G
WebSphere Commerce V7 Feature Pack 8 Management Center Functionality Updates	Commerce	https://yourlearning.w3bmix.ibm.com/#search/activities/q=6G65G
WebSphere Commerce V8 Developer Toolkit	Commerce	https://yourlearning.w3bmix.ibm.com/#search/activities/q=6G69G


